name: "Create Release"
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  create-octopus-release:
    name: "Create Octopus Release"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        octopus-project:
          - "Project1"
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Octopus Deploy
        uses: docker://octopusdeploy/octo
        env:
          OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
          OCTOPUS_SPACE_NAME: "Spaces-1"
      - run: |
          git log -1 --pretty=oneline
          commitMessage=$(git log -1 --pretty=oneline)
          echo $commitMessage
          jsonBody='{
            BuildEnvironment = "GitHub Actions"
            Branch = "${env:BRANCH_NAME}"
            BuildNumber = "${env:GITHUB_RUN_NUMBER}"
            BuildUrl = "https://github.com/${env:GITHUB_REPOSITORY}/actions/runs/${env:GITHUB_RUN_ID}"
            VcsCommitNumber = "${env:GITHUB_SHA}"
            VcsType = "Git"
            VcsRoot = "https://github.com/${env:GITHUB_REPOSITORY}.git"
            Commits = (
              {
                Id = "${env:GITHUB_SHA}"
                LinkUrl = "https://github.com/${env:GITHUB_REPOSITORY}/commit/${env:GITHUB_SHA}"
                Comment = $commitMessage
              }
            )
          }'
          echo $jsonBody > buildinformation.json
          echo "======================="
      - name: "Create ${{ matrix.octopus-project }} Octopus Release First"
        uses: docker://octopusdeploy/octo
        with:
          args: >
            build-information --package-id="${env:PACKAGE_NAME}" --file="buildinformation.json" --server=${{ secrets.OCTOPUS_SERVER_URL }} --apiKey=${{ secrets.OCTOPUS_API_KEY }} --space="${env:OCTOPUS_SPACE_NAME}"
      - name: "Create ${{ matrix.octopus-project }} Octopus Release Second"
        uses: docker://octopusdeploy/octo
        with:
          args: >
            octo create-release --project="${env:OCTOPUS_PROJECT_NAME}" --packageVersion="${env:PACKAGE_VERSION}"  --releaseNumber="${env:PACKAGE_VERSION}" --server="${env:OCTOPUS_URL}" --apiKey="${env:OCTOPUS_API_KEY}" --space="${env:OCTOPUS_SPACE_NAME}" --deployTo="${env:ENVIRONMENT_NAME}" --channel="${env:CHANNEL_NAME}" --variable="Feature Branch Name:${env:BRANCH_NAME}" --variable="Merged Branch Name:${env:MERGED_BRANCH}"