name: "Create Release"
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  create-octopus-release:
    name: "Create Octopus Release"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        octopus-project:
          - "Project1"
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Octopus Deploy
        uses: docker://octopusdeploy/octo
        env:
          OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
          OCTOPUS_SPACE_NAME: "Spaces-1"
      - run: |
          git log -1 --pretty=oneline
          commitMessage=$(git log -1 --pretty=oneline)
          echo $commitMessage
          jsonBody='{
            BuildEnvironment = "GitHub Actions"
            Branch = "${env:BRANCH_NAME}"
            BuildNumber = "${env:GITHUB_RUN_NUMBER}"
            BuildUrl = "https://github.com/${env:GITHUB_REPOSITORY}/actions/runs/${env:GITHUB_RUN_ID}"
            VcsCommitNumber = "${env:GITHUB_SHA}"
            VcsType = "Git"
            VcsRoot = "https://github.com/${env:GITHUB_REPOSITORY}.git"
            Commits = (
              {
                Id = "${env:GITHUB_SHA}"
                LinkUrl = "https://github.com/${env:GITHUB_REPOSITORY}/commit/${env:GITHUB_SHA}"
                Comment = $commitMessage
              }
            )
          }'
          echo $jsonBody > hello-world.1.0.0.zip.json
          readlink -f hello-world.1.0.0.zip.json
          echo "======================="
      - name: "Create ${{ matrix.octopus-project }} Octopus Release First"
        uses: docker://octopusdeploy/octo
        with:
          args: >
            build-information --package-id="hello-world.1.0.0.zip.json" --file="buildinformation.json" --version="hello-world.1.0.0.zip" --server=${{ secrets.OCTOPUS_SERVER_URL }} --apiKey=${{ secrets.OCTOPUS_API_KEY }} --space="Spaces-1"
      - name: "Create ${{ matrix.octopus-project }} Octopus Release Second"
        uses: docker://octopusdeploy/octo
        with:
          args: >
            octo create-release --project="Project1" --packageVersion="1124"  --releaseNumber="12412" --server=${{ secrets.OCTOPUS_SERVER_URL }} --apiKey=${{ secrets.OCTOPUS_API_KEY }} --space="Spaces-1"